os:
- linux
language: rust
rust:
- nightly
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libmysqlclient-dev
  - cargo install cargo-deb
script:
- tools/build.sh
deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  file_glob: true
  file: target/upload/*
  on:
    repo: udoprog/OxidizeBot
    tags: true
  api_key:
    secure: "cD/XoriyzKueusImd3c8V5v2LPnwi6gR/jlFpLz3lYOigZtJW5SK5T0+wvB/Shn8a8SxZUMP0BzroTKYiUizmwndjVOOGLRQbaxZiprHidY2QgpmDSqiX6FU5s8Yf3SH3JcwoiyGvv5hvzo9ovm6lGFntPqMEqN6wA4JAUTMebdICdEdsCXszcJz8DbTeQSoPZf04ouqOOuBJNL8tCe93O/i1ywe7ASXTGZMdFZrMfkrug8a5oaibZEM36mb/0hhkDzfxT39zrwyHwJXiDD13Lz2VNizQeR+itzMnAWQSyfVUVQeo5ww7kSHVF0Zvv0ky3dPjN9NVVMHlteYBHY3pVjs72Yw6CpKVMHDjl+dMS7S6/3fKcdPJnsZ6ssWyDdqVSJ0yBUEs/6KLNBEIQVG3APs2MCzcpR7PN4PJUflBLayG9HwofJFj+Lk1MzEW5Rxuds8PIKlOW5cqhkLsO2WzrC6q8LaaKZlqauxxnpvFUk2XC/y/CmROXvt8lLAQM3UX+wCfBtw0rV+/NCsgz7wYIAsKSkAF6DK0M0xctlX1pWfgOLTDQpgSUztYImAKgm/M7sCqY0nwcXO9YTS5Q1NXTnoTbYrfjj5CbK0yMJKX5+mywRYBC065ExcX/ERjLGApY8VRgSdxEOfCh+IOFfjHxLuhkW9sSmIAnyv0R9KXj8="