image: Visual Studio 2019

environment:
  SIGNTOOL: "C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.18362.0\\x64\\signtool.exe"
  matrix:
    - channel: beta
      target: x86_64-pc-windows-msvc

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %target% --default-toolchain %channel% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V
  - cargo install cargo-wix

build_script:
  - cargo run --manifest-path tools/builder/Cargo.toml

artifacts:
  - path: "*.zip"
    name: archive
  - path: "*.msi"
    name: installer

branches:
  only:
    - /^\d+\.\d+\.\d+(-[a-z]+\.\d+)?$/

deploy:
  - release: $(appveyor_repo_tag_name)
    provider: GitHub
    auth_token:
      secure: opsYSU1MsMMLlC3c/VJLZ0b4XGEMdVEJ0WZ2dRF+GtXjoVa5zy+wnxxrhg5gHP+G
    artifact: /.*\.(zip|msi)/
    draft: true
    prerelease: false
    on:
      APPVEYOR_REPO_TAG: true