image: Visual Studio 2017

environment:
  matrix:
    - channel: nightly
      target: x86_64-pc-windows-msvc

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %target% --default-toolchain %channel% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V
  - cargo install cargo-wix

build_script:
  - ps: .\tools\build.ps1

artifacts:
  - path: "*.zip"
    name: archive
  - path: "*.msi"
    name: installer

branches:
  only:
    - master
    - /\d+\.\d+\.\d+/
    - /point-\d+\.\d+/

deploy:
  - release: $(appveyor_repo_tag_name)
    provider: GitHub
    auth_token:
      secure: QlcWMc/7j2eVy1J8j0CFm3tUev+ZC6zXh7SrP2aFuE1trzhtf0IDbx2eTnYzta0h
    artifact: /.*\.(zip|msi)/
    draft: true
    prerelease: false
    on:
      APPVEYOR_REPO_TAG: true