[workspace]

default-members = ["bot"]
members = ["bot", "web"]
exclude = ["tools/builder"]

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
debug = true

[patch.crates-io]
tokio = { git = "https://github.com/udoprog/tokio", branch = "rwlock-map" }
rhai = { path = "../rhai" }
# rhai = { git = "https://github.com/jonathandturner/rhai" }