[package]
name = "oxidize-shared"
version = "0.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", features = ["derive"] }
toml = "0.5.3"