[package]
name = "oxidize"
version = "1.0.0-beta.18"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "High octane Twitch bot powered by Rust"

[dependencies]
chrono = { version = "0.4.9", features = ["serde"] }
chrono-tz = { version = "0.5.1", features = ["serde"] }
clap = "2.33.0"
mysql_async = "0.21.0-alpha.1"
diesel = { version = "1.4.2", features = ["sqlite", "chrono"] }
diesel_migrations = "1.4.0"
eudex = "0.1.1"
hashbrown = { version = "0.6.0", features = ["serde"] }
warp = { version = "0.1.20", git = "https://github.com/jxs/warp.git" }
log = "0.4.8"
oauth2 = {version = "2.0.0-alpha.5", git = "https://github.com/udoprog/oauth2-rs", branch = "async"}
relative-path = { version = "0.4.0", features = ["serde"] }
reqwest = { version = "0.10.0-alpha.0", git = "https://github.com/seanmonstar/reqwest.git", rev = "ebe57e10" }
serde = { version = "1.0.101", features = ["rc"] }
serde_yaml = "0.8.9"
serde_json = "1.0.40"
serde_cbor = "0.10.1"
serde_urlencoded = "0.6.1"
tokio = "0.2.0-alpha.5"
tokio-executor = "0.2.0-alpha.5"
url = { version = "2.1", features = ["serde"] }
Inflector = "0.11.4"
rspotify = "0.6.0"
base64 = "0.10.1"
rand = "0.7.2"
fixed-map = "0.6.1"
log4rs = "0.8.3"
handlebars = "2.0.2"
htmlescape = "0.3.1"
lazy_static = "1.4.0"
# set the bundled feature to use the bundled libsqlite3
libsqlite3-sys = { version = "0.12.0", features = ["bundled", "unlock_notify"] }
webbrowser = "0.5.2"
parking_lot = "0.9.0"
err-derive = "0.1.5"
percent-encoding = "2.1.0"
bytes = "0.4.12"
websocket = "0.23.0"
uuid = { version = "0.7.4", features = ["serde", "v4"] }
pin-utils = "0.1.0-alpha.4"
smallvec = { version = "0.6.10", features = ["serde"] }
dirs = "2.0.2"
backoff = "0.1.5"
rust-embed = { version = "5.1.0", features = ["interpolate-folder-path"] }
mime = "0.3.14"
mime_guess = "2.0.1"
uom = "0.25.0"
crossbeam = "0.7.2"
hex = "0.4.0"
graphql_client = "0.8.0"
futures-option = "0.1.2"
futures-cache = "0.7.1"
failure = "0.1.5"
async-injector = "0.2.2"
async-trait = "0.1.13"
leaky-bucket = { version = "0.3.1",  features = ["tokio02"] }
regex = "1.3.1"
backtrace = "0.3.38"

[dependencies.tracing]
version = "0.1"

[dependencies.tracing-core]
version = "0.1"

[dependencies.tracing-futures]
git = "https://github.com/tokio-rs/tracing.git"
features = ["tokio-alpha"]

[dependencies.irc]
version = "0.13.6"
git = "https://github.com/udoprog/irc.git"
branch = "next"

[dependencies.futures]
package = "futures-preview"
version = "0.3.0-alpha.18"

[build-dependencies]
winres = "0.1.11"
failure = "0.1.5"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.8", features = ["shellapi", "impl-default"] }

[features]
default = ["windows"]
windows = []
