[package]
name = "setmod-web"
version = "0.0.2"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
hyper = "0.12.24"
tokio = "0.1.15"
failure = "0.1"
serde = {version = "1.0.88", features = ["rc"]}
serde_json = "1.0.38"
handlebars = "1.1.0"
futures = "0.1.25"
log = "0.4"
pretty_env_logger = "0.3"
reqwest = "0.9.10"
chrono = {version = "0.4.6", features = ["serde"]}
hashbrown = "0.1.8"
clap = "2.32"