[package]
name = "oxidize-web"
version = "0.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
bytes = "0.4.12"
hyper = "0.13.0-alpha.2"
tower-service = "0.3.0-alpha.1"
tokio = "0.2.0-alpha.5"
failure = "0.1.5"
serde = { version = "1.0.100", features = ["rc", "derive"] }
serde_json = "1.0.39"
serde_cbor = "0.10.1"
toml = "0.5.3"
serde_urlencoded = "0.6.1"
futures-preview = {version = "0.3.0-alpha.18", features = ["nightly", "async-await"]}
log = "0.4.6"
pretty_env_logger = "0.3.0"
reqwest = { version = "0.10.0-alpha.0", git = "https://github.com/seanmonstar/reqwest.git", rev = "ebe57e10" }
chrono = { version = "0.4.6", features = ["serde"] }
clap = "2.33.0"
rust-embed = { version = "5.1.0", features = ["interpolate-folder-path"] }
mime_guess = "2.0.1"
mime = "0.3.14"
smallvec = "0.6.10"
cookie = { version = "0.12.0", features = ["percent-encode"] }
base64 = "0.10.1"
time = "0.1.42"
oauth2 = {version = "2.0.0-alpha.5", git = "https://github.com/udoprog/oauth2-rs", branch = "async"}
url = { version = "2.1.0", features = ["serde"] }
parking_lot = "0.9.0"
sled = "0.28.0"
ring = "0.16.9"
relative-path = {version = "0.4.0", features = ["serde"]}