[package]
name = "oxidize-web"
version = "0.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
bytes = "0.4.12"
hyper = "0.13.0-alpha.2"
tower-service = "0.3.0-alpha.1"
tokio = "0.2.0-alpha.5"
failure = "0.1.5"
serde = { version = "1.0.100", features = ["rc", "derive"] }
serde_json = "1.0.39"
handlebars = "1.1.0"
futures-preview = "0.3.0-alpha.18"
log = "0.4.6"
pretty_env_logger = "0.3.0"
reqwest = { version = "0.10.0-alpha.0", git = "https://github.com/seanmonstar/reqwest" }
chrono = { version = "0.4.6", features = ["serde"] }
hashbrown = "0.3.0"
clap = "2.33.0"