[package]
name = "oxidize-web"
version = "0.0.2"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
hyper = "0.12.29"
tokio = "0.1.20"
failure = "0.1.5"
serde = { version = "1.0.91", features = ["rc"] }
serde_json = "1.0.39"
handlebars = "1.1.0"
futures = "0.1.27"
log = "0.4.6"
pretty_env_logger = "0.3.0"
reqwest = "0.9.17"
chrono = { version = "0.4.6", features = ["serde"] }
hashbrown = "0.3.0"
clap = "2.33.0"
